name: Run Cypress Tests

on:
    pull_request:
        branches:
            - main

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: yarn build
              env:
                  VITE_QRCODE_CONTRACT_ADDRESS: "0xB21f93840906Ea9CD07194F4367c2BB5C120BBB3"

            - name: Start server
              run: yarn dev --port 3000 &
              env:
                  VITE_QRCODE_CONTRACT_ADDRESS: "0xB21f93840906Ea9CD07194F4367c2BB5C120BBB3"

            - name: Wait for server to start
              run: sleep 30

            - name: Run Cypress tests
              run: npx cypress run
              env:
                  VITE_QRCODE_CONTRACT_ADDRESS: "0xB21f93840906Ea9CD07194F4367c2BB5C120BBB3"
